[package]
name = "blockchain_1"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono="0.4"
sha2="0.10"
serde={version="1.0" ,features=["derive"]}
serde_json="1.0"
rsa="0.9.2"
rand="0.8"
base64="0.22"
p256={version="0.13",features=["ecdsa"]}
tokio={version="1",features=["full"]}